// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://omvhttowoiuwnygzkydz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9tdmh0dG93b2l1d255Z3preWR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYxMDA1ODcsImV4cCI6MjA1MTY3NjU4N30.w7vKdjffNQpZhiL-AdY3KxM3-JmnnkC52KCII3Fuv9U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);